### ISSUE TITLE
关于自动生成侧边栏

### ISSUE THREAD

**Issue by vayocc** [Xaviw/XaviDocs#1]
我从 bying搜到您的[ 这篇文章](https://xaviw.github.io/XaviDocs/%E5%B7%A5%E5%85%B7%E7%B3%BB%E5%88%97/VitePress%E6%90%AD%E5%BB%BA/%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90%E7%9B%AE%E5%BD%95.html) 来，但是我看到本仓库里好像没有用到自动生成 侧边栏和导航栏，把他注释掉了，请问是什么原因呢？  因为想要一个可以根据目录生成侧边栏的功能，特意请教。

**Comment by Xaviw** [comment]
因为我之前用到的生成方案不能完全符合我的需求，可能也无法适配最新的 vitepress 1.0，最近会尝试修改

**Comment by vayocc** [comment]
好的吧，怪不得。

**Comment by vayocc** [comment]
此问题我想了两种解决方案，
1.根据文档目录写通用映射方法自动化，（这样话有个缺点就是侧边栏不够灵活，毕竟都约定限制了）
2.根据目录生成侧边栏对应的 JSON ，这样也方便后期修改，（这也有缺点，就是减少了手写JSON的过程，但是还是需要自己贴上去。）

**Comment by Xaviw** [comment]
最新插件已发布，可以查看 [npm](https://www.npmjs.com/package/vite-plugin-vitepress-auto-nav) 或 [介绍文章](https://xaviw.github.io/XaviDocs/%E5%B7%A5%E5%85%B7%E7%B3%BB%E5%88%97/VitePress%E6%90%AD%E5%BB%BA/%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90%E7%9B%AE%E5%BD%95.html)
