### ISSUE TITLE
(login or auth ) (登录或者鉴权)

### ISSUE THREAD

**Issue by nogeek-cn** [Xaviw/XaviDocs#31]
老哥，如何做一个登录的接口，然后让 登录的用户才能看某些文章？？？老哥有没有计划开发一个这个插件？？？

**Comment by Xaviw** [comment]
你是说自己实现登录还是用第三方登录？没想过有这个需求，要实现的话就和做管理系统一样，可以改写下导航组件，从后端获取文章列表渲染

基本就是自定义组件和对接后端实现逻辑这么个方式

**Comment by nogeek-cn** [comment]
目录是全部都可以看到，就是文章内容，从后端获取，这种，这种插件，老哥有计划开发么？

**Comment by Xaviw** [comment]
这个需求太定制化了，感觉不通用啊🤪就对接服务器这块做成插件就不太合适，还是需要自己去实现逻辑，当成一个项目做，就不只是用 vitepress 提供的功能了

**Comment by nogeek-cn** [comment]
我是做后端的，不懂前端，在想如果能做一个付费订阅的博客网站感觉就不错了。所以问问老哥有没有 auth0 的什么集成什么的？

**Comment by nogeek-cn** [comment]
我想明白了，这个需求本质上是一个 构建一个 空的 MD，
MD 引入一个 VUE 组件，就是渲染这个 VUE 组件就行了。
这个 VUE 组件在网页渲染的时候，读取，网页的链接，然后，截取掉域名。
 URI +一个 header 里的 Token 传递给后端的接口，
后端返回 MD 文件，
VUE 把 MD 文件渲染在页面上。实现这个需求。

**Comment by Xaviw** [comment]
原理上是这样的，但 vitepress 是打包过程中转换 md 为展示页面，所以网络获取 md 并渲染还要自己在 vue 组件中加上转换 md 为 html 的逻辑

你的需求还是需要自己定义实现，因为需要结合后端，不是一个很通用的场景，我自身也没这样的需求，不适合做成插件。但是你不懂前端的话会比较麻烦，可以借助 ChatGPT 尝试实现，或者去了解下其他有这方面功能的工具
