### ISSUE TITLE
nav 添加自定义链接

### ISSUE THREAD

**Issue by nogeek-cn** [Xaviw/XaviDocs#33]
![image](https://github.com/Xaviw/XaviDocs/assets/37619525/6dcbc744-351f-4916-b403-16778c19e56e)

点击某个 nav 跳转到别的地方？

我想在标题上，添加一个 自定义链接，跳转到别的地方，可以实现吗？？？？
怎么做？？？

**Comment by nogeek-cn** [comment]
# nav 和你的 AutoNav 会冲突吗？

**Comment by nogeek-cn** [comment]
需要用你的 autoNav 和 nav 一起使用，好像不能一起用

**Comment by Xaviw** [comment]
nav存在手动配置时就不会再自动生成了，因为nav项都较少，没考虑到这个需求
